# 운영 환경 설정
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:MARUNI-DB}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  jpa:
    hibernate:
      ddl-auto: validate  # 운영환경에서는 validate 사용
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# 운영환경 쿠키 설정 (보안 강화)
cookie:
  secure: true

# 운영환경 Swagger 설정
swagger:
  server:
    url: ${SWAGGER_SERVER_URL:https://api.yourdomain.com}
    description: 운영 서버

# 운영환경 로깅 (ERROR 레벨만)
logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.type.descriptor.sql.BasicBinder: warn
    com.example.login: info
    root: warn