server:
  port: 8080

spring:
  profiles:
    active: dev
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:application-ai.yml
      - classpath:application-security.yml
      - classpath:application-swagger.yml
      - classpath:application-maruni.yml
      - classpath:application-firebase.yml