# Firebase & Push Notification 설정 파일
# Spring Boot Profile: firebase

# Firebase 설정
firebase:
  enabled: ${FIREBASE_ENABLED:false}  # 기본값: false (개발환경에서는 Mock 사용)
  project-id: ${FIREBASE_PROJECT_ID:maruni-dev}
  service-account-key-path: ${FIREBASE_SERVICE_ACCOUNT_KEY_PATH:config/firebase-service-account-key.json}
  push:
    timeout: 5000  # 5초
    retry:
      max-attempts: 3
      backoff-multiplier: 2.0
      initial-delay: 1000  # 1초