server:
  port: 8080

spring:
  profiles:
    active: dev # 기본 프로파일: dev
  config:
    import:
      - optional:file:.env[.properties]

# 공통 보안 설정
security:
  public-urls:
    - "/api-docs"
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
  cors-max-age: 3600

# 공통 JWT 설정
jwt:
  secret-key: ${JWT_SECRET_KEY:your_jwt_secret_key_at_least_32_characters}
  access-token:
    expiration: ${JWT_ACCESS_EXPIRATION:3600000}  # 1시간 (밀리초)
  refresh-token:
    expiration: ${JWT_REFRESH_EXPIRATION:1209600000}  # 14일 (밀리초)

# 공통 Swagger 설정
springdoc:
  swagger-ui:
    path: /api-docs