server:
  port: 8080

spring:
  profiles:
    active: dev
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:application-ai.yml

# 공통 보안 설정
security:
  public-urls:
    - "/api-docs"
    - "/v3/api-docs/**"
    - "/swagger-ui/**"

# 공통 JWT 설정
jwt:
  secret-key: ${JWT_SECRET_KEY:your_jwt_secret_key_at_least_32_characters}
  access-token:
    expiration: ${JWT_ACCESS_EXPIRATION:3600000}  # 1시간 (밀리초)
  refresh-token:
    expiration: ${JWT_REFRESH_EXPIRATION:1209600000}  # 14일 (밀리초)

# 공통 Swagger 설정
swagger:
  api:
    title: "MARUNI API Documentation"
    description: "REST API Documentation for MARUNI elderly care service"
    version: "v1.0.0"
  contact:
    name: "MARUNI Development Team"
    email: "dev@maruni.com"
    url: "https://github.com/maruni-project"
  server:
    url: "http://localhost:8080"
    description: "Development Server"

springdoc:
  swagger-ui:
    path: /api-docs

# Phase 2 MVP 스케줄링 & 푸시 알림 설정
maruni:
  scheduling:
    daily-check:
      cron: "0 0 9 * * *" # 매일 오전 9시
      batch-size: 50
      timeout-seconds: 30
    retry:
      cron: "0 */5 * * * *" # 5분마다
      max-retries: 3
      delay-minutes: 5

  notification:
    push:
      enabled: true # MVP에서는 푸시 알림만 활성화
      provider: "firebase"
      project-id: ${FIREBASE_PROJECT_ID:maruni-project}

  # AlertRule 도메인 설정 (Phase 1 리팩토링)
  alert:
    analysis:
      default-days: 7
    emotion:
      high-risk-consecutive-days: 3
      high-risk-negative-ratio: 0.7
      medium-risk-consecutive-days: 2
      medium-risk-negative-ratio: 0.5
    keyword:
      emergency:
        - "도와주세요"
        - "아파요"
        - "숨이"
        - "가슴이"
        - "쓰러짐"
        - "응급실"
        - "119"
        - "병원"
        - "죽겠어"
      warning:
        - "우울해"
        - "외로워"
        - "죽고싶어"
        - "포기"
        - "희망없어"
        - "의미없어"
        - "괴로워"
        - "힘들어"
    notification:
      title-template: "[MARUNI 알림] %s 단계 이상징후 감지"
      detection-details-json-template: "{\"alertLevel\":\"%s\",\"analysisDetails\":\"%s\"}"
      notification-failure-log: "Guardian notification failed for member: %d"
      notification-error-log: "Error sending guardian notification: %s"
    no-response:
      high-risk-consecutive-no-response-days: 2
      high-risk-min-response-rate: 0.3
      medium-risk-consecutive-no-response-days: 1
      medium-risk-min-response-rate: 0.5

  encryption:
    algorithm: "AES/GCM/NoPadding"
    key: ${ENCRYPTION_KEY:default_encryption_key_32_bytes}